### ISSUE TITLE
Build info properties are not being shown

### ISSUE THREAD

**Issue by kapoormanish** [mjhugo/grails-build-info#13]
Build info properties are not being shown, however Runtime application status and Installed Plugins are being shown(see attached screenshot). I need to see the date/time the war file was built and Git Revision Number. 
I did following to integrate the plugin in my grails **2.5.1** application:

1. Added `compile "org.grails.plugins:build-info:1.2.8"` in BuildConfig.groovy.

2.  Added below line in Config.groovy to secure the url for only APP_ADMIN:
`'/buildInfo/**'       : ['hasRole("APP_ADMIN")']`

Am I missing something?
![build info](https://cloud.githubusercontent.com/assets/4479013/13742518/2c93a33c-ea02-11e5-8fd7-9cbf88fe20dd.png)

**Comment by rlovtangen** [comment]
Can you take a look at `WEB-INF/classes/application.properties` in the generated war file?
````
unzip -p target/myapp-0.1.war WEB-INF/classes/application.properties
````
Does it contain properties `scm.version` and `build.date`?

**Comment by kapoormanish** [comment]
@rlovtangen I just found that It works when I create the war file and deploy it in Tomcat. However, it does not work when I run application locally by `grails run-app`.

**Comment by rlovtangen** [comment]
Correct

**Comment by kapoormanish** [comment]
Thanks for the quick response.
